In [1]:
library(ggplot2)
options(repr.plot.height=4,repr.plot.width=6)

Cargar los datos en un dataframe llamado: airbnb

In [2]:
airbnb<-read.csv('data//airbnb.csv',sep = ',')

Mostrar las primeras 6 filas del dataframe

In [3]:
airbnb[1:6,]
#También se puede usar
head(airbnb)

Zipcode Neighbourhood.Cleansed Property.Type Room.Type       Accommodates
1 28004   Universidad            Apartment     Private room    2           
2 28004   Universidad            Apartment     Entire home/apt 6           
3 28004   Universidad            Apartment     Entire home/apt 3           
4 28004   Universidad            Loft          Entire home/apt 3           
5 28015   Universidad            Apartment     Entire home/apt 5           
6 28004   Universidad            Apartment     Entire home/apt 2           
  Bathrooms Bedrooms Beds Bed.Type
1 2         1        1    Real Bed
2 1         3        5    Real Bed
3 1         2        2    Real Bed
4 2         1        1    Real Bed
5 1         1        1    Real Bed
6 1         0        1    Real Bed
  Amenities                                                                                                                                                                                                                                                                                                                                                       
1 TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron                                                                                                                                                                             
2 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo                                                                                                                                                                                     
3 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace                                                                                                                                                                                          
4 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50                                          
5 TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron                                                                                                                                                                                                              
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1  NA         35     NA                 
2  NA         92     96                 
3  NA         55     91                 
4  NA         60    100                 
5 538         75     90                 
6  NA         55     95

Zipcode Neighbourhood.Cleansed Property.Type Room.Type       Accommodates
1 28004   Universidad            Apartment     Private room    2           
2 28004   Universidad            Apartment     Entire home/apt 6           
3 28004   Universidad            Apartment     Entire home/apt 3           
4 28004   Universidad            Loft          Entire home/apt 3           
5 28015   Universidad            Apartment     Entire home/apt 5           
6 28004   Universidad            Apartment     Entire home/apt 2           
  Bathrooms Bedrooms Beds Bed.Type
1 2         1        1    Real Bed
2 1         3        5    Real Bed
3 1         2        2    Real Bed
4 2         1        1    Real Bed
5 1         1        1    Real Bed
6 1         0        1    Real Bed
  Amenities                                                                                                                                                                                                                                                                                                                                                       
1 TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron                                                                                                                                                                             
2 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo                                                                                                                                                                                     
3 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace                                                                                                                                                                                          
4 TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50                                          
5 TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron                                                                                                                                                                                                              
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1  NA         35     NA                 
2  NA         92     96                 
3  NA         55     91                 
4  NA         60    100                 
5 538         75     90                 
6  NA         55     95

Renombrar las columnas de la siguiente forma:

| Nombre original | Nuevo nombre |
| - | - |
| Zipcode | CodigoPostal |
| Neighbourhood.Cleansed | Barrio |
| Property.Type	| TipoPropiedad |
| Room.Type | TipoAlquiler |
| Accommodates | MaxOcupantes |
| Bathrooms	| NumBanyos |
| Bedrooms	| NumDormitorios |
| Beds	|  NumCamas |
| Bed.Type	| TipoCama |
| Amenities | Comodidades |
| Square.Feet | PiesCuadrados |
| Price	| Precio |
| Review.Scores.Rating | Puntuacion |

In [4]:
newnames<-c("CodigoPostal","Barrio","TipoPropiedad","TipoAlquiler","MaxOcupantes","NumBanyos",
"NumDormitorios","NumCamas","TipoCama","Comodidades","PiesCuadrados","Precio","Puntuacion")
colnames(airbnb)<-newnames

Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.

Ayuda: 1 pie cuadrado son 0,092903 metros cuadrdados

In [5]:
airbnb["MetrosCuadrados"]<-airbnb$PiesCuadrados*0.092903

Miremos el código postal. Es una variable con entradas erroneas.
Hay valores como '', '-'  y '28' que deberían ser considerados como NA.
Así mismo también debería ser NA todos los que no compiencen por 28, ya que estamos con códigos postales de Madrid

El código postal 28002, 28004 y 28051 tienen entradas repetidas. 
Por ejemplo las entradas 28002\n20882 deberían ir dnetro de 28002

El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 juncto con 2815 debería ser 28015

Limpia los datos de la columna Codigo Postal

In [6]:
# Hago una comprobación visual rápida de los errores que tenemos
levels(airbnb$CodigoPostal)

[1] ""             "-"            "20013"        "20126"        "2015"        
 [6] "25008"        "27004"        "27013"        "28"           "28001"       
[11] "280013"       "28002"        "28002\n28002" "28003"        "28004"       
[16] "28005"        "28006"        "28007"        "28008"        "28009"       
[21] "28010"        "28011"        "28012"        "28013"        "28014"       
[26] "28015"        "28016"        "28017"        "28018"        "28019"       
[31] "28020"        "28021"        "28022"        "28023"        "28024"       
[36] "28025"        "28026"        "28027"        "28028"        "28029"       
[41] "28030"        "28031"        "28032"        "28033"        "28034"       
[46] "28035"        "28036"        "28037"        "28038"        "28039"       
[51] "2804"         "28040"        "28041"        "28042"        "28043"       
[56] "28044"        "28045"        "28046"        "28047"        "28048"       
[61] "28049"        "2805"         "28050"        "28051"        "28051\n28051"
[66] "28052"        "28053"        "28054"        "28055"        "28056"       
[71] "28058"        "28060"        "28094"        "28105"        "2815"        
[76] "28850"        "Madrid 28004"

In [7]:
# Compruebo específicamente cuantos valores diferentes hay con información que he visto que podría salvarse
levels(airbnb$CodigoPostal)[which(grepl("\n", levels(airbnb$CodigoPostal)))]
levels(airbnb$CodigoPostal)[which(grepl("Madrid", levels(airbnb$CodigoPostal)))]

[1] "28002\n28002" "28051\n28051"

[1] "Madrid 28004"

In [8]:
#Modifico los valores anteriores
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "28002\n28002"] <- "28002"
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "28051\n28051"] <- "28051"
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "Madrid 28004"] <- "28004"

In [9]:
#Paso los valores a tipo numérico para que todo lo que no sean números se convierta a NA
levels(airbnb$CodigoPostal) <- as.numeric(levels(airbnb$CodigoPostal))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”


In [10]:
#Compruebo códigos postales con incorrecta longitud
levels(airbnb$CodigoPostal)[nchar(levels(airbnb$CodigoPostal)) != 5]

[1] "2015"   "28"     "280013" "2804"   "2805"   "2815"

In [11]:
#Salvo los valores que se pueden salvar
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "280013"] <- "28013"
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "2804"] <- "28004"
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "2805"] <- "28005"
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) == "2815"] <- "28015"

In [12]:
#Convierto en NA los códigos postales inferiores a 28000 y superiores a 28999 (no comienzan por 28)
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) > 28999] <- NA
levels(airbnb$CodigoPostal)[levels(airbnb$CodigoPostal) < 28000] <- NA

In [13]:
#Elimino todos los NA
airbnb <- airbnb[complete.cases(airbnb$CodigoPostal),]

Una vez limpios los datos ¿Cuales son los códigos postales que tenemos? 

In [14]:
airbnb$CodigoPostal

[1] 28004 28004 28004 28004 28015 28004 28004 28004 28015 28004 28004 28004
   [13] 28013 28005 28013 28013 28013 28012 28013 28013 28013 28005 28013 28012
   [25] 28012 28013 28014 28013 28012 28005 28005 28005 28005 28012 28005 28005
   [37] 28045 28005 28005 28005 28005 28005 28013 28013 28013 28013 28013 28012
   [49] 28013 28012 28013 28013 28013 28012 28013 28013 28012 28045 28045 28045
   [61] 28045 28045 28045 28045 28045 28045 28045 28045 28045 28012 28045 28045
   [73] 28045 28045 28012 28012 28012 28012 28005 28012 28005 28012 28012 28012
   [85] 28012 28012 28005 28012 28005 28005 28012 28005 28012 28012 28005 28005
   [97] 28005 28012 28012 28005 28012 28014 28014 28014 28014 28012 28014 28014
  [109] 28014 28012 28014 28014 28014 28014 28014 28012 28012 28014 28012 28012
  [121] 28005 28012 28012 28012 28012 28012 28005 28005 28012 28012 28012 28012
  [133] 28005 28012 28012 28014 28014 28045 28045 28045 28045 28007 28007 28007
  [145] 28007 28007 28007 28028 28009 28009 28009 28009 28014 28014 28007 28005
  [157] 28013 28005 28005 28013 28013 28013 28005 28013 28013 28005 28005 28005
  [169] 28013 28013 28013 28005 28013 28005 28013 28013 28005 28013 28005 28013
  [181] 28013 28005 28005 28013 28013 28005 28013 28005 28013 28005 28013 28005
  [193] 28005 28005 28005 28005 28013 28005 28005 28005 28013 28013 28012 28005
  [205] 28012 28005 28012 28005 28012 28012 28005 28012 28005 28012 28012 28012
  [217] 28012 28012 28012 28012 28012 28012 28013 28013 28014 28012 28012 28012
  [229] 28005 28005 28005 28012 28012 28005 28012 28012 28012 28012 28012 28012
  [241] 28012 28014 28014 28014 28014 28012 28014 28014 28014 28014 28004 28004
  [253] 28004 28004 28004 28004 28004 28004 28004 28004 28001 28001 28006 28001
  [265] 28001 28001 28001 28001 28001 28001 28006 28009 28009 28009 28009 28006
  [277] 28009 28006 28006 28028 28028 28028 28004 28004 28004 28004 28004 28004
  [289] 28004 28004 28004 28004 28004 28004 28004 28004 28004 28004 28004 28004
  [301] 28004 28004 28004 28004 28015 28004 28004 28004 28015 28004 28004 28015
  [313] 28004 28004 28004 28004 28004 28013 28015 28004 28015 28004 28004 28004
  [325] 28015 28004 28004 28004 28015 28015 28015 28015 28015 28015 28015 28010
  [337] 28015 28010 28010 28010 28010 28010 28010 28010 28004 28010 28010 28010
  [349] 28028 28028 28028 28028 28006 28006 28006 28006 28002 28002 28006 28002
  [361] 28002 28034 28050 28008 28011 28011 28049 28038 28053 28038 28047 28011
  [373] 28011 28011 28011 28011 28011 28011 28047 28011 28011 28011 28011 28025
  [385] 28019 28019 28024 28019 28019 28019 28019 28019 28025 28019 28002 28002
  [397] 28002 28016 28016 28036 28016 28016 28016 28036 28016 28046 28039 28039
  [409] 28020 28020 28020 28020 28020 28020 28003 28029 28029 28029 28020 28015
  [421] 28015 28015 28015 28015 28015 28015 28015 28015 28015 28010 28003 28003
  [433] 28003 28003 28003 28003 28029 28008 28008 28008 28008 28008 28015 28008
  [445] 28008 28008 28008 28008 28008 28008 28008 28025 28025 28025 28054 28025
  [457] 28041 28041 28026 28026 28026 28038 28053 28058 28053 28053 28018 28018
  [469] 28018 28053 28053 28030 28030 28030 28017 28017 28027 28027 28027 28027
  [481] 28027 28027 28027 28027 28027 28043 28033 28043 28043 28033 28033 28033
  [493] 28033 28033 28033 28041 28050 28055 28021 28041 28032 28032 28032 28032
  [505] 28037 28037 28022 28027 28042 28004 28004 28004 28004 28004 28004 28004
  [517] 28015 28004 28004 28004 28004 28004 28094 28013 28013 28005 28005 28005
  [529] 28013 28005 28005 28013 28005 28005 28005 28005 28005 28013 28013 28005
  [541] 28013 28009 28001 28001 28009 28001 28001 28001 28001 28001 28028 28001
  [553] 28006 28028 28028 28028 28028 28012 28012 28012 28012 28013 28014 28012
  [565] 28012 28013 28005 28013 28013 28013 28012 28013 28013 28045 28045 28045
  [577] 28045 28045 28045 28045 28045 28045 28045 28012 28045 28012 28045 28003
  [589] 28015 28003 28003 28046 28029 28039 28039 28039 28039 28015 28015 28015
  [6

¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?

In [15]:
#Uso la función table para realizar el conteo.
#Los ordeno con sort de manera descendente y selecciono los cinco primeros índices
#Muestro en forma de dataframe los códigos postales resultantes y el número de veces que aparece cada uno

#Códigos postales con más entradas
as.data.frame(sort(table(airbnb$CodigoPostal), decreasing = T)[1:5])

Var1  Freq
1 28012 2060
2 28004 1796
3 28005 1195
4 28013 1020
5 28014  630

In [16]:
#Códigos postales con menos entradas
df1 <- as.data.frame(sort(table(airbnb$CodigoPostal)))
df1[df1$Freq == 1,]
#Selecciono todos los que aparecen una sola vez,
#ya que hay más de 5 y no tendría sentido escoger "los 5 con menos entradas"

Var1  Freq
1 28048 1   
2 28052 1   
3 28056 1   
4 28058 1   
5 28060 1   
6 28094 1   
7 28105 1   
8 28850 1

¿Cuales son los barrios que hay en el código postal 28012?

In [17]:
#Selecciono de la columna "Barrio" los índices que se correspondan con el código postal 28012
#Utilizo la función unique para que no me muestre resultados repetidos
unique(airbnb[airbnb$CodigoPostal == 28012, "Barrio"])

[1] Sol             Acacias         Palos de Moguer Embajadores    
 [5] Cortes          Palacio         Universidad     Delicias       
 [9] Arapiles        Atocha          Goya           
125 Levels: Abrantes Acacias Adelfas Aeropuerto Aguilas ... Zofío

¿Cuantas entradas hay en cada uno de esos barrios para el codigo postao 28012? Asumiendo que el identificador de Barrio sea correcto, ¿es fiable la columna de código postal?

In [18]:
#Selecciono de los barrios los índices que se correspondan con el código postal 28012
#Uso table para realizar el conteo de los resultados y lo convierto en dataframe
#Muestro todos aquellos barrios que hayan tenido al menos una aparición (frecuencia distinta a 0)
barrios <- as.data.frame(table(airbnb$Barrio[airbnb$CodigoPostal == 28012]))
barrios[barrios$Freq != 0,]

Var1            Freq
2   Acacias           13
14  Arapiles           1
18  Atocha             1
41  Cortes           216
45  Delicias           1
49  Embajadores     1449
56  Goya               1
81  Palacio           27
85  Palos de Moguer   46
112 Sol              301
115 Universidad        4

In [19]:
#Compruebo los códigos postales que coinciden con los tres barrios con más apariciones
#De este modo compruebo de un vistazo la fiabilidad
unique(airbnb[airbnb$Barrio == "Embajadores", "CodigoPostal"])
unique(airbnb[airbnb$Barrio == "Sol", "CodigoPostal"])
unique(airbnb[airbnb$Barrio == "Cortes", "CodigoPostal"])

[1] 28012 28005 28014 28045
61 Levels: 28001 28013 28002 28003 28004 28005 28006 28007 28008 ... 28850

[1] 28013 28005 28012 28014 28004 28016 28034 28015 28001
61 Levels: 28001 28013 28002 28003 28004 28005 28006 28007 28008 ... 28850

[1] 28012 28014 28004 28013 28033 28008
61 Levels: 28001 28013 28002 28003 28004 28005 28006 28007 28008 ... 28850

¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?

In [20]:
barrios <- levels(airbnb$Barrio)
cat("Hay",length(barrios),"barrios.")
barrios

Hay 125 barrios.

[1] "Abrantes"                     "Acacias"                     
  [3] "Adelfas"                      "Aeropuerto"                  
  [5] "Aguilas"                      "Alameda de Osuna"            
  [7] "Almagro"                      "Almenara"                    
  [9] "Almendrales"                  "Aluche"                      
 [11] "Ambroz"                       "Amposta"                     
 [13] "Apostol Santiago"             "Arapiles"                    
 [15] "Aravaca"                      "Arcos"                       
 [17] "Argüelles"                    "Atocha"                      
 [19] "Bellas Vistas"                "Berruguete"                  
 [21] "Buenavista"                   "Butarque"                    
 [23] "Campamento"                   "Canillas"                    
 [25] "Canillejas"                   "Cármenes"                    
 [27] "Casa de Campo"                "Casco Histórico de Barajas"  
 [29] "Casco Histórico de Vallecas"  "Casco Histórico de Vicálvaro"
 [31] "Castellana"                   "Castilla"                    
 [33] "Castillejos"                  "Chopera"                     
 [35] "Ciudad Jardín"                "Ciudad Universitaria"        
 [37] "Colina"                       "Comillas"                    
 [39] "Concepción"                   "Corralejos"                  
 [41] "Cortes"                       "Costillares"                 
 [43] "Cuatro Caminos"               "Cuatro Vientos"              
 [45] "Delicias"                     "El Goloso"                   
 [47] "El Plantío"                   "El Viso"                     
 [49] "Embajadores"                  "Entrevías"                   
 [51] "Estrella"                     "Fontarrón"                   
 [53] "Fuente del Berro"             "Fuentelareina"               
 [55] "Gaztambide"                   "Goya"                        
 [57] "Guindalera"                   "Hellín"                      
 [59] "Hispanoamérica"               "Ibiza"                       
 [61] "Imperial"                     "Jerónimos"                   
 [63] "Justicia"                     "La Paz"                      
 [65] "Legazpi"                      "Lista"                       
 [67] "Los Angeles"                  "Los Rosales"                 
 [69] "Lucero"                       "Marroquina"                  
 [71] "Media Legua"                  "Mirasierra"                  
 [73] "Moscardó"                     "Niño Jesús"                  
 [75] "Nueva España"                 "Numancia"                    
 [77] "Opañel"                       "Orcasitas"                   
 [79] "Orcasur"                      "Pacífico"                    
 [81] "Palacio"                      "Palomas"                     
 [83] "Palomeras Bajas"              "Palomeras Sureste"           
 [85] "Palos de Moguer"              "Pavones"                     
 [87] "Peñagrande"                   "Pilar"                       
 [89] "Pinar del Rey"                "Piovera"                     
 [91] "Portazgo"                     "Pradolongo"                  
 [93] "Prosperidad"                  "Pueblo Nuevo"                
 [95] "Puerta Bonita"                "Puerta del Angel"            
 [97] "Quintana"                     "Recoletos"                   
 [99] "Rejas"                        "Rios Rosas"                  
[101] "Rosas"                        "Salvador"                    
[103] "San Andrés"                   "San Cristobal"               
[105] "San Diego"                    "San Fermín"                  
[107] "San Isidro"                   "San Juan Bautista"           
[109] "San Pascual"                  "Santa Eugenia"               
[111] "Simancas"                     "Sol"                         
[113] "Timón"                        "Trafalgar"                   
[115] "Universidad"                  "Valdeacederas"               
[117] "Valdefuentes"                 "Valdemarín"         

¿Cuales son los 5 barrios que tienen mayor número entradas?

In [21]:
#Uso la función table para realizar el conteo.
#Los ordeno con sort de manera descendente y selecciono los cinco primeros índices
#Muestro en forma de dataframe los barrios resultantes y el número de veces que aparece cada uno
as.data.frame(sort(table(airbnb$Barrio), decreasing = T)[1:5])

Var1        Freq
1 Embajadores 1800
2 Universidad 1326
3 Palacio     1055
4 Sol          908
5 Justicia     765

¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?

In [22]:
cat("Hay",length(levels(airbnb$TipoAlquiler)),"tipos de alquiler")

#Muestro en forma de dataframe los tipos de alquiler que hay y el número de veces que aparece cada uno
as.data.frame(sort(table(airbnb$TipoAlquiler)))

Hay 3 tipos de alquiler

Var1            Freq
1 Shared room      180
2 Private room    4898
3 Entire home/apt 7682

Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler

Cual es el precio medio de alquiler medio de cada uno, la diferencia que hay ¿es estadísticamente significativa?
¿Con que test lo comprobarías?

Filtra el dataframe cuyos tipo de alquiler sea  'Entire home/apt' y guardalo en un dataframe llamado 
*airbnb_entire*.
Estas serán las entradas que tienen un alquiler del piso completo.

¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler?
Nota: Mirar solo en airbnb_entire

¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros?

¿Cual es su precio medio?

Ayuda: Usa la función aggregate `aggregate(.~colname,df,mean,na.rm=TRUE)`

¿Cuantos apartamentos hay en cada uno de esos barrios?

Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas.

Ayuda: Podeis crear un nuevo dataframe con las columnas "Barrio" y "Freq" que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.

Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.

Dibuja el diagrama de densidad de distribución de los diferentes precios

Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas

Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos

Esta claro que las medias de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes?
¿Que test habría que usar para comprobarlo?

Para únicamente los pisos de alquiler en el barrio de Sol:

``barrio_sol<-subset(airbnb_entire,Barrio=="Sol")``

Calcular un modelo lineal que combine alguna de estas variables:
* NumBanyos
* NumDormitorios
* MaxOcupantes
* MetrosCuadrados

Primero calculamos la correlación para ver como se relacionan estas variables entre sí.

Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja.
¿Son de fiar esos números?

Mediante un histograma o curvas de densidad podemos descartar números que notienen sentido en el dataframe barrio_sol,
para tener una matriz de correlación que tenga mayor sentido.


Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble.

¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?

Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?

Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?

¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios?
¿Cual es el margen de error de esa probabilidad?